### ISSUE TITLE
Fiji versioning

### ISSUE THREAD

**Issue by grahampugh** [autopkg/rtrouton-recipes#177]
Hi Rich,

I've been taking a look at the Fiji.download recipe. The version that's reported is problematic in that the version you get from https://wsr.imagej.net/notes.html refers to ImageJ, not Fiji specifically. We can get Fiji versions from the tags at https://github.com/fiji/fiji/tags, but these go newer than the releases. 

The release at https://downloads.imagej.net/fiji/latest/ is not versioned, but it also appears not to be the latest at all. The latest is available, with version string, from https://downloads.imagej.net/fiji/releases/

However, on further investigation, it seems that pushing the newest version in "releases" is risky. 

Finally, I looked at what Homebrew are doing, and they've come up with the idea of grabbing the datestamp of the latest version. They note that a new folder is added to the "archive" folder shortly after the latest release is created, into which that release is copied. This happens around 30 minutes after the date stamp of the latest release, so is a good indicator, and easier to scrape than that actual date stamp.

I've built a recipe based on this for our own purposes but feel free to adapt your "official" one with the logic below. 

```yaml
Input:
  NAME: Fiji

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: (\d{8}-\d{4})
      url: https://downloads.imagej.net/fiji/archive/?C=N;O=D
      result_output_var_name: version

  - Processor: URLDownloader
    Arguments:
      filename: "%NAME%-%version%.zip"
      url: "https://downloads.imagej.net/fiji/latest/fiji-macosx.zip"

  - Processor: EndOfCheckPhase

```
